#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
import helpers

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # get tweets
    get_tweets = helpers.get_user_timeline

    # analyze tweets 
    screen_name = sys.argv[1]
    all_tweets = get_tweets(screen_name, count = 50)
    for tweet in all_tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}", "green").format(score, tweet))
        elif score < 0.0:
            print(colored("{} {}", "red").format(score, tweet))
        else:
            print(colored("{} {}", "yellow").format(score, tweet))

if __name__ == "__main__":
    main()    

